[site]
title = "Kaiyi Chen"
description = "Personal website of Kaiyi Chen at Sichuan University."
favicon = "/trans_logo.png"
last_updated = "July 14, 2026"

[author]
name = "Kaiyi Chen"
title = "Master's Student"
institution = "AECC Sichuan Gas Turbine Establishment"
avatar = "/avatar.webp"

[social]
# Contact information (leave blank or delete to hide)

email = "kaiyi0365@163.com"
location = "Chengdu, China"
location_details = [
  "520 Tongren Road,",
  "Xindu District, Chengdu, China"
]
orcid = "https://orcid.org/0009-0003-5217-7238"
github = "https://github.com/ChenKai22567"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, the site remembers the language preference in browser localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
